AppChat/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.principal, name='principal'),
    path('chat', views.chat, name='chat')

]

AppMatricula/urls.py
from django.urls import path, include
from . import views

urlpatterns = [
    path('matricula', views.matricula, name='matricula')

]

confini/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('AppChat.urls')),
    path('AppChat/', include(('AppChat.urls','AppChat'), namespace='AppChat')),
    path('AppMatricula/', include(('AppMatricula.urls','AppMatricula'), namespace='AppMatricula')),
]

AppChat/models.py
from django.db import models

# Create your models here.

AppMatricula/models.py
from django.db import models

# Create your models here.

AppChat/views.py
from django.http import request
from django.shortcuts import render

# Create your views here.
def principal(request):
    return render(request, "principal/home.html")

def chat(request):
    return render(request, 'AppChat/chat.html')

AppMatricula/views.py
from django.http import request
from django.shortcuts import render

# Create your views here.
def matricula(request):
    return render(request, "AppMatricula/matricula.html")

templates/AppChat/chat.html
{% extends 'principal/home.html'%}
{% block titulo %} Chat {% endblock titulo%}
<div class="container">
    {% block contenido %}
    <h1>Bienvenido al Chat</h1>
    {% endblock contenido %}

  </div>
  

templates/AppMatricula/matricula.html
{% extends 'principal/home.html'%}
{% block titulo %} Matricula {% endblock titulo%}
<div class="container">
    {% block contenido %}
    <h1>Matriculas</h1>
    {% endblock contenido %}

  </div>
  

templates/principal/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <title>{% block titulo %}Inicio{% endblock titulo%}</title>
    <nav style="background-color: green;">
        <div class="nav-wrapper">
          <a href="#" class="brand-logo">Blog</a>
          <ul id="nav-mobile" class="right hide-on-med-and-down">
            <li><a href="{% url 'principal'%}">Inicio</a></li>
            <li><a href="{% url 'AppMatricula:matricula'%}">Matricula</a></li>
            <li><a href="{% url 'AppChat:chat'%}">Chat</a></li>
          </ul>
        </div>
      </nav>
</head>
<body>
    <div class="container">
        {% block contenido %}
        <h1>Bienvenido a mi pagina web</h1>
        {% endblock contenido %}
    
      </div>
      
    
</body>
</html>